### ISSUE TITLE
Running from F# interactive

### ISSUE THREAD

**Issue by pasho** [fsprojects/FSharp.Azure.Storage#11] opened 2015-09-04 21:42 UTC
Hi!

I was trying to put together a simple script, which would insert some records to an Azure Table.
```f#
#r @"..\packages\FSharp.Azure.Storage.2.0.0\lib\net45\FSharp.Azure.Storage.dll"
#r @"..\packages\WindowsAzure.Storage.3.1.0.1\lib\net40\Microsoft.WindowsAzure.Storage.dll"

open System
open FSharp.Azure.Storage
open FSharp.Azure.Storage.Table
open Microsoft.WindowsAzure.Storage
open Microsoft.WindowsAzure.Storage.Table

type Cluster = {     
    [<PartitionKey>]Partition: string;
    [<RowKey>]RowKey: string;
    ...
}


let account = CloudStorageAccount.Parse "UseDevelopmentStorage=true;" //Or your connection string here
let tableClient = account.CreateCloudTableClient()

let insertClusters clusters =
    let ops = clusters |> Seq.map(fun c -> InsertOrReplace(c))
    ops |> inTableAsBatch tableClient "Clusters" 
```

 I keep getting a weird error:
error FS0074: The type referenced through 'Microsoft.WindowsAzure.Storage.Table.CloudTableClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.WindowsAzure.Storage'.

Looks like I have that reference. What else do I need to add?

**Comment by isaacabraham** [comment] 2015-09-05 09:14
I suspect that the wrong version of the storage dll is being picked up.  See if in the output window you can see which version is being picked up. It could also be one of the child dependencies like OData and Edm etc.

You might need to explicitly set some #I to guide fsi correctly.

**Comment by takemyoxygen** [comment] 2015-10-11 13:46
I'm getting the same error when using `FSharp.Azure.Storage.2.1.0` and `WindowsAzure.Storage.3.1.0.1`. I installed these packages to an empty F# console app and now trying to load assemblies to FSI. To load assemblies I use the following script (initially generated using "Generate references for F# Interactive" but I modified it to explicitly do #I before loading an assembly)
```fsharp
// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__

#I @"..\..\packages\FSharp.Azure.Storage.2.1.0\lib\net45"
#r @"..\..\packages\FSharp.Azure.Storage.2.1.0\lib\net45\FSharp.Azure.Storage.dll"

#I @"..\..\packages\FSharp.Data.2.2.5\lib\net40"
#r @"..\..\packages\FSharp.Data.2.2.5\lib\net40\FSharp.Data.dll"

#I @"..\..\packages\FSPowerPack.Core.Community.2.0.0.0\lib\Net40"
#r @"..\..\packages\FSPowerPack.Core.Community.2.0.0.0\lib\Net40\FSharp.PowerPack.dll"

#I @"..\..\packages\FSPowerPack.Linq.Community.3.0.0.0\lib\Net40"
#r @"..\..\packages\FSPowerPack.Linq.Community.3.0.0.0\lib\Net40\FSharp.PowerPack.Linq.dll"

#I @"..\..\packages\Microsoft.Data.Edm.5.6.0\lib\net40"
#r @"..\..\packages\Microsoft.Data.Edm.5.6.0\lib\net40\Microsoft.Data.Edm.dll"

#I @"..\..\packages\Microsoft.Data.OData.5.6.0\lib\net40"
#r @"..\..\packages\Microsoft.Data.OData.5.6.0\lib\net40\Microsoft.Data.OData.dll"

#I @"..\..\packages\Microsoft.Data.Services.Client.5.6.0\lib\net40"
#r @"..\..\packages\Microsoft.Data.Services.Client.5.6.0\lib\net40\Microsoft.Data.Services.Client.dll"

#I @"..\..\packages\Microsoft.WindowsAzure.ConfigurationManager.1.8.0.0\lib\net35-full"
#r @"..\..\packages\Microsoft.WindowsAzure.ConfigurationManager.1.8.0.0\lib\net35-full\Microsoft.WindowsAzure.Configuration.dll"

#I @"..\..\packages\WindowsAzure.Storage.3.1.0.1\lib\net40"
#r @"..\..\packages\WindowsAzure.Storage.3.1.0.1\lib\net40\Microsoft.WindowsAzure.Storage.dll"

#I @"..\..\packages\Newtonsoft.Json.5.0.6\lib\net45"
#r @"..\..\packages\Newtonsoft.Json.5.0.6\lib\net45\Newtonsoft.Json.dll"

#I @"..\..\packages\Suave.0.32.0\lib\net40"
#r @"..\..\packages\Suave.0.32.0\lib\net40\Suave.dll"
#r @"System.Core.dll"
#r @"System.Data.dll"
#r @"System.dll"
#r @"System.Numerics.dll"

#I @"..\..\packages\System.Spatial.5.6.0\lib\net40"
#r @"..\..\packages\System.Spatial.5.6.0\lib\net40\System.Spatial.dll"

#r @"System.Xml.dll"
#r @"System.Xml.Linq.dll"
```

and when I'm trying to execute this script
```fsharp
#load "Scripts/load-references2.fsx"

open FSharp.Azure.Storage.Table
open Microsoft.WindowsAzure.Storage

[<Literal>]
let connectionString = "my-connection-string"

type UserFavourites =
    { [<RowKey>] Id: string;
      [<PartitionKey>] Source: string
      Favourites: string}

let account = CloudStorageAccount.Parse connectionString
let tableClient = account.CreateCloudTableClient()

fromTable tableClient "favourites" Query.all<UserFavourites> // this is line 17
|> Seq.iter(fun (x, _) -> printfn "%A" x)
```
I get an error
```
Script.fsx(17,1): error FS0074: The type referenced through 'Microsoft.WindowsAzure.Storage.Table.CloudTableClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.WindowsAzure.Storage'.
```

The output of F# interactive shows paths of loaded assemblies (look correct to me):
```
--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts' to library include path

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSharp.Azure.Storage.2.1.0\lib\net45' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSharp.Azure.Storage.2.1.0\lib\net45\FSharp.Azure.Storage.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSharp.Data.2.2.5\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSharp.Data.2.2.5\lib\net40\FSharp.Data.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSPowerPack.Core.Community.2.0.0.0\lib\Net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSPowerPack.Core.Community.2.0.0.0\lib\Net40\FSharp.PowerPack.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSPowerPack.Linq.Community.3.0.0.0\lib\Net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\FSPowerPack.Linq.Community.3.0.0.0\lib\Net40\FSharp.PowerPack.Linq.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.Data.Edm.5.6.0\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.Data.Edm.5.6.0\lib\net40\Microsoft.Data.Edm.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.Data.OData.5.6.0\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.Data.OData.5.6.0\lib\net40\Microsoft.Data.OData.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.Data.Services.Client.5.6.0\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.Data.Services.Client.5.6.0\lib\net40\Microsoft.Data.Services.Client.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.WindowsAzure.ConfigurationManager.1.8.0.0\lib\net35-full' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Microsoft.WindowsAzure.ConfigurationManager.1.8.0.0\lib\net35-full\Microsoft.WindowsAzure.Configuration.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\WindowsAzure.Storage.3.1.0.1\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\WindowsAzure.Storage.3.1.0.1\lib\net40\Microsoft.WindowsAzure.Storage.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Newtonsoft.Json.5.0.6\lib\net45' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Newtonsoft.Json.5.0.6\lib\net45\Newtonsoft.Json.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Suave.0.32.0\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\Suave.0.32.0\lib\net40\Suave.dll'

--> Referenced 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Core.dll'
--> Referenced 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Data.dll'
--> Referenced 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.dll'
--> Referenced 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Numerics.dll'

--> Added 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\System.Spatial.5.6.0\lib\net40' to library include path
--> Referenced 'C:\Users\uladz\code\temp\RefsTest\RefsTest\Scripts\..\..\packages\System.Spatial.5.6.0\lib\net40\System.Spatial.dll'

--> Referenced 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Xml.dll'
--> Referenced 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Xml.Linq.dll'
```

But if I compile the same code and run it as a console app, it works just fine.

Any ideas?

**Comment by daniel-chambers** [comment] 2015-10-13 08:57
Are you using VS2013 or VS2015?

**Comment by takemyoxygen** [comment] 2015-10-13 16:04
I'm using 2015

**Comment by daniel-chambers** [comment] 2015-10-14 09:50
I'm able to reproduce this in VS2015 rather than VS2013. Seems like it's caused by using F# 4.0 rather than 3.1, but I don't know why that would be. :(

**Comment by daniel-chambers** [comment] 2015-10-14 09:57
Here's a workaround I've discovered. If you move the #r statement for WindowsAzure.Storage above the one for FSharp.Azure.Storage then the problem goes away. Make sure you reset your FSI session trying to run the changed scripts first, otherwise it doesn't work. I'm not even sure why it does work at all to be honest!

**Comment by takemyoxygen** [comment] 2015-10-14 18:09
Unbelievable! It does for me as well, thanks!

**Comment by daniel-chambers** [comment] 2015-10-14 22:23
Cool. I'm going to close this issue, as I don't think this is a problem in this project, though it may be an issue in FSI. If you don't agree, please reopen.

**Closed by daniel-chambers** 2015-10-14 22:23 UTC

**Comment by isaacabraham** [comment] 2015-10-15 09:07
Did you see if there was any spurious output in FSI when calling code? Sometimes it binds to the wrong version of an assembly e.g. It'll bind to versions of azure assemblies that are in the SDK folder rather than the NuGet package folder. Changing the order of #r or adding extra #I can often fix this problem.
